name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Install .NET Framework 4.6.1 Developer Pack
      run: choco install netfx-4.6.1-devpack -y
      shell: pwsh
      
    - name: Restore NuGet packages
      run: |
        # First try with solution file if it exists
        if (Test-Path "*.sln") {
          $solutionFile = Get-ChildItem -Path "*.sln" | Select-Object -First 1
          nuget restore $solutionFile
        } else {
          # Otherwise specify packages directory
          nuget restore Commons_Automation\Commons_Automation.csproj -PackagesDirectory packages
        }
      shell: pwsh
      
    - name: Build
      run: msbuild Commons_Automation\Commons_Automation.csproj /p:Configuration=Release
      
    - name: Test
      run: dotnet test --configuration Release --no-build
        # Replace with your actual test command
        # For example, using VSTest:
        # "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" Commons_Automation\bin\Release\Commons_Automation.dll
