name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Checkout the repository
    - uses: actions/checkout@v4

    # Install .NET Framework 4.6.1 Developer Pack
    - name: Install .NET Framework 4.6.1 Developer Pack
      run: |
        $url = "https://download.microsoft.com/download/8/E/6/8E6A8349-2D34-4C54-9C42-9E4C9E8A8E8F/NDP461-DevPack-KB3105179-ENU.exe"
        $output = "$env:TEMP\ndp461-devpack.exe"
        Invoke-WebRequest -Uri $url -OutFile $output
        Start-Process -FilePath $output -ArgumentList "/q /norestart" -Wait -NoNewWindow
      shell: pwsh # Use PowerShell for this step

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build
      run: dotnet build --no-restore

    # Run tests
    - name: Test
      run: dotnet test --no-build --verbosity normal
