name: .NET
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
      
    - name: Install .NET Framework 4.6.1 Developer Pack
      run: choco install netfx-4.6.1-devpack -y
      shell: pwsh
      
    - name: Restore NuGet packages
      run: |
        if (Test-Path "*.sln") {
          $solutionFile = Get-ChildItem -Path "*.sln" | Select-Object -First 1
          nuget restore $solutionFile
        } else {
          nuget restore Commons_Automation\Commons_Automation.csproj -PackagesDirectory packages
        }
      shell: pwsh
      
    - name: Build
      run: msbuild Commons_Automation\Commons_Automation.csproj /p:Configuration=Release
      
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1
      
    - name: Test
      run: vstest.console.exe Commons_Automation\bin\Release\Commons_Automation.dll
