name: .NET Test Automation

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.201'  # Specify your .NET version here

    - name: Restore dependencies
      run: dotnet restore Commons_Automation/Commons_Automation.csproj
        # Explicitly specify the .csproj file to ensure correct restoration

    - name: Build
      run: dotnet build Commons_Automation/Commons_Automation.csproj --no-restore
        # Match the build to the same project file

    - name: Run tests
      run: dotnet test Commons_Automation/Commons_Automation.csproj --no-build --verbosity normal
