name: .NET Test Automation

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.201'  # Specify your .NET version here

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore
