name: .NET Test Automation

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.201'

    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear

    - name: Setup NuGet
      run: curl -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
      shell: cmd

    - name: Restore NuGet packages
      run: nuget.exe restore Commons_Automation/Commons_Automation.csproj -PackagesDirectory ..\packages
      shell: cmd

    - name: Build with MSBuild
      run: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Commons_Automation/Commons_Automation.csproj -t:Build -p:Configuration=Release'
      shell: cmd

    - name: Run tests
      run: dotnet test Commons_Automation/Commons_Automation.csproj --no-build --verbosity normal
