name: .NET Test Automation

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: self-hosted
    env:
      PACKAGES_DIR: ${{ github.workspace }}\packages
      MSBUILD_PATH: "C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\MSBuild\\Current\\Bin\\MSBuild.exe"

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.201'

    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear

    - name: Setup NuGet
      run: curl -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
      shell: cmd

    - name: Restore NuGet packages
      run: nuget.exe restore Commons_Automation/Commons_Automation.csproj -PackagesDirectory "%PACKAGES_DIR%" -Verbosity detailed
      shell: cmd

    - name: Build with MSBuild
      run: '"%MSBUILD_PATH%" Commons_Automation/Commons_Automation.csproj -t:Build -p:Configuration=Release'
      shell: cmd

    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1

    - name: Test
      run: vstest.console.exe Commons_Automation\bin\Release\Commons_Automation.dll /Tests:ASCadminPage /Settings:"Commons_Automation\runsettings.QA.runsettings" /Logger:trx;LogFileName=test-results.trx
      shell: cmd

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results.trx
