name: .NET Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted  # Your self-hosted runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Fetches your repository code

      - name: Restore dependencies
        run: dotnet restore  # Uses the existing .NET SDK

      - name: Build
        run: dotnet build --no-restore  # Builds the solution

      - name: Run tests
        run: dotnet test --no-build --verbosity normal  # Runs tests
