name: .NET Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.201' # Updated to your SDK version

    - name: Restore dependencies
      run: dotnet restore --project Pranjal_Commons_Git_Actions/Commons_Automation.sln

    - name: Build the project
      run: dotnet build --configuration Release --no-restore --property:Platform="Any CPU" --project Pranjal_Commons_Git_Actions/Commons_Automation.sln

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal --project Pranjal_Commons_Git_Actions/Commons_Automation.sln
