name: .NET Test Automation

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '9.0.201'

    - name: Clear NuGet cache
      run: dotnet nuget locals all --clear

    - name: Setup NuGet
      run: curl -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
      shell: cmd

    - name: Restore NuGet packages
      run: nuget.exe restore Commons_Automation/Commons_Automation.csproj -PackagesDirectory C:\actions-runner\_work\Pranjal_Commons_Git_Actions\Pranjal_Commons_Git_Actions\packages -Verbosity detailed
      shell: cmd

    - name: Verify NuGet packages
      run: dir C:\actions-runner\_work\Pranjal_Commons_Git_Actions\Pranjal_Commons_Git_Actions\packages
      shell: cmd

    - name: Build with MSBuild
      run: '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe" Commons_Automation/Commons_Automation.csproj -t:Build -p:Configuration=Release'
      shell: cmd

    - name: Run Tests and Generate Report
      run: |
        dotnet test Commons_Automation\Commons_Automation.csproj `
          --configuration Release `
          --no-build `
          --logger "trx;LogFileName=test-results.trx" `
          --filter "TestCategory=ASCadminPage" `
          --settings Commons_Automation\runsettings.QA.runsettings
      shell: powershell

    - name: Publish Test Results
      uses: actions/upload-artifact@v2
      if: always()  # Uploads report even if tests fail
      with:
        name: Test Results
        path: TestResults/test-results.trx

    - name: Display Test Summary
      run: |
        $trxPath = "TestResults/test-results.trx"
        if (Test-Path $trxPath) {
          $xml = [xml](Get-Content $trxPath)
          $passed = $xml.TestRun.ResultSummary.Counters.passed
          $failed = $xml.TestRun.ResultSummary.Counters.failed
          Write-Output "Test Results Summary:"
          Write-Output "✅ Passed: $passed"
          Write-Output "❌ Failed: $failed"
        } else {
          Write-Output "No test results found!"
        }
      shell: powershell
